# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
# This line might not be necessary depending on your environment setup
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../flatforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSACipherWindow(object):
    def setupUi(self, RSACipherWindow):
        RSACipherWindow.setObjectName("RSACipherWindow")
        RSACipherWindow.resize(1076, 513)
        self.centralwidget = QtWidgets.QWidget(RSACipherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_top.addWidget(self.labelTitle)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem1)
        self.btnGenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateKeys.setObjectName("btnGenerateKeys")
        self.horizontalLayout_top.addWidget(self.btnGenerateKeys)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem2)
        self.verticalLayout_main.addLayout(self.horizontalLayout_top)
        self.horizontalLayout_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.gridLayout_leftTop = QtWidgets.QGridLayout()
        self.gridLayout_leftTop.setObjectName("gridLayout_leftTop")
        self.verticalLayout_left.addLayout(self.gridLayout_leftTop)
        self.horizontalLayout_leftButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_leftButtons.setObjectName("horizontalLayout_leftButtons")
        self.verticalLayout_left.addLayout(self.horizontalLayout_leftButtons)
        self.horizontalLayout_main.addLayout(self.verticalLayout_left)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.gridLayout_rightTop = QtWidgets.QGridLayout()
        self.gridLayout_rightTop.setObjectName("gridLayout_rightTop")
        self.labelInformation = QtWidgets.QLabel(self.centralwidget)
        self.labelInformation.setObjectName("labelInformation")
        self.gridLayout_rightTop.addWidget(self.labelInformation, 0, 0, 1, 1)
        self.textEditInfo = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditInfo.sizePolicy().hasHeightForWidth())
        self.textEditInfo.setSizePolicy(sizePolicy)
        self.textEditInfo.setMinimumSize(QtCore.QSize(0, 100))
        self.textEditInfo.setObjectName("textEditInfo")
        self.gridLayout_rightTop.addWidget(self.textEditInfo, 0, 1, 1, 1)
        self.labelSignature = QtWidgets.QLabel(self.centralwidget)
        self.labelSignature.setObjectName("labelSignature")
        self.gridLayout_rightTop.addWidget(self.labelSignature, 1, 0, 1, 1)
        self.textEditSignature = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditSignature.sizePolicy().hasHeightForWidth())
        self.textEditSignature.setSizePolicy(sizePolicy)
        self.textEditSignature.setMinimumSize(QtCore.QSize(0, 100))
        self.textEditSignature.setObjectName("textEditSignature")
        self.gridLayout_rightTop.addWidget(self.textEditSignature, 1, 1, 1, 1)
        self.verticalLayout_right.addLayout(self.gridLayout_rightTop)
        self.horizontalLayout_rightButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_rightButtons.setObjectName("horizontalLayout_rightButtons")
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_rightButtons.addItem(spacerItem3)
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setObjectName("btnSign")
        self.horizontalLayout_rightButtons.addWidget(self.btnSign)
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setObjectName("btnVerify")
        self.horizontalLayout_rightButtons.addWidget(self.btnVerify)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_rightButtons.addItem(spacerItem4)
        self.verticalLayout_right.addLayout(self.horizontalLayout_rightButtons)
        self.horizontalLayout_main.addLayout(self.verticalLayout_right)
        self.verticalLayout_main.addLayout(self.horizontalLayout_main)
        RSACipherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RSACipherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menubar.setObjectName("menubar")
        RSACipherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RSACipherWindow)
        self.statusbar.setObjectName("statusbar")
        RSACipherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RSACipherWindow)
        QtCore.QMetaObject.connectSlotsByName(RSACipherWindow)

    def retranslateUi(self, RSACipherWindow):
        _translate = QtCore.QCoreApplication.translate
        RSACipherWindow.setWindowTitle(_translate("RSACipherWindow", "RSA CIPHER"))
        self.labelTitle.setText(_translate("RSACipherWindow", "ECC CIPHER"))
        self.btnGenerateKeys.setText(_translate("RSACipherWindow", "Generate Keys"))
        self.labelInformation.setText(_translate("RSACipherWindow", "Information:"))
        self.labelSignature.setText(_translate("RSACipherWindow", "Signature:"))
        self.btnSign.setText(_translate("RSACipherWindow", "Sign"))
        self.btnVerify.setText(_translate("RSACipherWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSACipherWindow = QtWidgets.QMainWindow()
    ui = Ui_RSACipherWindow()
    ui.setupUi(RSACipherWindow)
    RSACipherWindow.show()
    sys.exit(app.exec_())
